#!/usr/bin/env python3
"""
VTEX Algolia Path Runner (Help Center & Dev Portal)

Runs queries from all_queries.json against the Algolia Search API for
Help Center (index: helpcenter-docs) and/or Dev Portal (index: devportal-docs).
Outputs results in the unified format documented in
docs/test-suite/results-layout.md.

Query source: data/test-suite/internal-search/all_queries.json (Internal search path)
Fallback: Individual issue files from docs/test-suite/issues/ (if all_queries.json not found)

Usage:
    python tools/test-suite/internal-search/run-algolia-path.py [--path helpcenter|devportal|both] [options]

Options:
    --path TEXT                       Path(s) to run: helpcenter, devportal, or both (default: both)
    --run-id TEXT                     Run identifier (default: algolia-{path}-run-YYYY-MM-DD-HHmmss)
    --issues TEXT                     Space-separated issue IDs to filter (default: all)
    --top-n INT                       Number of top results to capture (default: 10)
    --output-dir TEXT                 Base output directory (default: results/internal-search)
    --delay FLOAT                     Delay between API calls in seconds (default: 0.5)
    --locale TEXT                     Locale filter for search (default: all, options: en, es, pt, all)
    --no-analysis                     Skip per-index markdown analysis reports (generated by default)

Environment (any of these):
    ALGOLIA_APP_ID / NEXT_PUBLIC_ALGOLIA_APP_ID     Algolia Application ID (required)
    ALGOLIA_SEARCH_API_KEY / ALGOLIA_SEARCH_KEY     Search-only key (preferred)
    NEXT_PUBLIC_ALGOLIA_WRITE_KEY                   Write key (also works for search in this script)
"""

import os
import sys
import re
import json
import time
import urllib.request
import urllib.error
import ssl
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from collections import defaultdict

# Add current directory to path for shared utilities (test_runner_utils.py is in the same directory)
_script_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(_script_dir))

# Import shared utilities
from test_runner_utils import (
    load_env_file,
    parse_issue_file,
    normalize_url,
    check_expected_doc_found,
    truncate_text,
    validate_output_directory,
    load_issues_from_directory,
    load_issues_from_all_queries_json,
    format_result_for_display,
    calculate_statistics,
    group_results_by_style,
    deduplicate_results_by_document,
    TITLE_MAX_LENGTH,
    URL_DISPLAY_MAX_LENGTH,
    QUERY_DISPLAY_MAX_LENGTH,
    ERROR_MESSAGE_MAX_LENGTH,
)

# Load environment variables from .env file if it exists
load_env_file()

# Algolia index names (from helpcenter/algolia and devportal/algolia configs)
ALGOLIA_INDEX_HELPCENTER = "helpcenter-docs"
ALGOLIA_INDEX_DEVPORTAL = "devportal-docs"

def create_run_directory(base_output: Path, path_slug: str, timestamp: datetime | None = None) -> Path:
    """Create a per-run output folder under results/internal-search/<variant>/."""
    ts = timestamp or datetime.now()
    folder_name = f"{path_slug} {ts.strftime('%Y-%m-%d %H-%M')}"
    variant_root = base_output / path_slug
    run_dir = variant_root / folder_name
    if not run_dir.exists():
        run_dir.mkdir(parents=True, exist_ok=False)
        return run_dir

    suffix = 2
    while True:
        candidate = variant_root / f"{folder_name} ({suffix})"
        if not candidate.exists():
            candidate.mkdir(parents=True, exist_ok=False)
            return candidate
        suffix += 1


def call_algolia_search(
    application_id: str,
    api_key: str,
    index_name: str,
    query: str,
    hits_per_page: int = 10,
    locale: Optional[str] = None,
    timeout: int = 30,
) -> tuple[dict, list[str]]:
    """
    Call Algolia Search API (POST /1/indexes/{indexName}/query).

    Returns:
        Tuple of (full response dict, list of error strings).
    """
    url = f"https://{application_id}.algolia.net/1/indexes/{index_name}/query"
    body_params = {
        "query": query,
        "hitsPerPage": hits_per_page,
        "page": 0,
        "attributesToRetrieve": ["hierarchy", "content", "url", "doctype", "language", "doctitle", "docCategory", "method"],
        "attributesToSnippet": ["content:50"],
        "attributesToHighlight": ["hierarchy", "content"],
    }
    if locale:
        body_params["filters"] = f"language:{locale}"
    body = json.dumps(body_params).encode("utf-8")

    headers = {
        "X-Algolia-Application-Id": application_id,
        "X-Algolia-API-Key": api_key,
        "Content-Type": "application/json",
    }

    errors = []
    try:
        ctx = ssl.create_default_context()
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        errors.append(f"HTTP {e.code}: {e.reason}")
        return {}, errors
    except urllib.error.URLError as e:
        errors.append(f"URL error: {e.reason}")
        return {}, errors
    except TimeoutError:
        errors.append(f"Request timed out after {timeout}s")
        return {}, errors
    except Exception as e:
        errors.append(str(e))
        return {}, errors

    return data, []


def hit_to_top_result(hit: dict, rank: int) -> dict:
    """Map an Algolia hit to { rank, url, title } for §4.6 top_results."""
    url = hit.get("url") or hit.get("url_without_anchor") or ""
    hierarchy = hit.get("hierarchy") or {}
    # Prefer doctitle, then lvl0, then content snippet
    title = (
        hit.get("doctitle")
        or hierarchy.get("lvl0")
        or (hit.get("content") or "")[:80]
        or "(no title)"
    )
    # Truncate title if too long
    title = truncate_text(title, TITLE_MAX_LENGTH)
    return {"rank": rank, "url": url, "title": title}


def run_one_path(
    path_name: str,
    index_name: str,
    issues: list[dict],
    application_id: str,
    api_key: str,
    run_id: str,
    top_n: int,
    delay: float,
    locale: Optional[str] = None,
) -> dict:
    """Run all query_internal queries for one Algolia path. Return unified results dict."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    path_slug = f"algolia-{path_name}"
    
    # Apply index-specific locale filtering
    # helpcenter-docs: must run for all locales
    # devportal-docs: must run ONLY for 'en' locale
    if path_name == "devportal":
        # Filter out non-English queries for devportal
        filtered_issues = []
        for issue in issues:
            queries = issue.get("query_internal", [])
            en_queries = [q for q in queries if q.get("locale", "en") == "en"]
            if en_queries:
                filtered_issue = issue.copy()
                filtered_issue["query_internal"] = en_queries
                filtered_issues.append(filtered_issue)
        issues = filtered_issues
        print(f"  Note: devportal-docs index only supports 'en' locale. Filtered to English queries only.")

    results = {
        "run_id": run_id,
        "path": path_slug,
        "timestamp": timestamp,
        "config": {
            "algolia_index": index_name,
            "locale": locale or "all",
            "top_n": top_n,
            "issues_count": len(issues),
            "queries_count": sum(len(i.get("query_internal", [])) for i in issues),
        },
        "summary_by_issue": [],
        "errors": [],
        "results": [],
    }

    total_issues = len(issues)

    for issue_idx, issue in enumerate(issues, start=1):
        issue_id = issue["issue_id"]
        target_url = issue.get("target_doc_url", issue.get("expected_doc_url", ""))
        queries = issue.get("query_internal", [])

        print(f"\n[Issue {issue_idx}/{total_issues}] {issue_id}")

        issue_summary = {
            "issue_id": issue_id,
            "target_doc_url": target_url,
            "expected_doc_url": target_url,
            "results_by_style": {},
            "best_rank": None,
            "worst_rank": None,
            "pass": False,
        }
        ranks_found = []

        for query_idx, qo in enumerate(queries, start=1):
            query_text = qo.get("query", "")
            query_style = qo.get("style", "unknown")
            query_locale = qo.get("locale", locale or "en")  # Use query-specific locale or fallback

            print(f"  [{query_idx}/{len(queries)} ({query_style}, {query_locale})] {query_text[:50]}...")

            time.sleep(delay)

            response_data, api_errors = call_algolia_search(
                application_id, api_key, index_name, query_text, hits_per_page=top_n, locale=query_locale
            )

            if api_errors:
                print(f"    ERROR: {api_errors[0]}")
                results["errors"].append(
                    {
                        "issue_id": issue_id,
                        "query": query_text,
                        "query_style": query_style,
                        "error_type": "api_call_failed",
                        "error_message": api_errors[0],
                    }
                )
                results["results"].append(
                    {
                        "issue_id": issue_id,
                        "path": path_slug,
                        "query": query_text,
                        "query_style": query_style,
                        "query_locale": query_locale,
                        "target_doc_url": target_url,
                        "expected_doc_url": target_url,
                        "found": False,
                        "found_at_rank": None,
                        "top_results": [],
                        "algolia_response": {},
                    }
                )
                issue_summary["results_by_style"][query_style] = {
                    "found": False,
                    "rank": None,
                }
                continue

            hits = response_data.get("hits", [])
            top_results = [
                hit_to_top_result(hit, i)
                for i, hit in enumerate(hits[:top_n], start=1)
            ]
            found, found_at_rank = check_expected_doc_found(top_results, target_url)
            status = f"found at rank {found_at_rank}" if found else "not found"
            print(f"    -> {len(hits)} hits | Target doc: {status}")

            results["results"].append(
                {
                    "issue_id": issue_id,
                    "path": path_slug,
                    "query": query_text,
                    "query_style": query_style,
                    "query_locale": query_locale,
                    "target_doc_url": target_url,
                    "expected_doc_url": target_url,
                    "found": found,
                    "found_at_rank": found_at_rank,
                    "target_doc_url_found": found,
                    "target_doc_url_rank": found_at_rank,
                    "top_results": top_results,
                    "algolia_response": response_data,
                }
            )
            issue_summary["results_by_style"][query_style] = {
                "found": found,
                "rank": found_at_rank,
            }
            if found and found_at_rank:
                ranks_found.append(found_at_rank)

        if ranks_found:
            issue_summary["best_rank"] = min(ranks_found)
            issue_summary["worst_rank"] = max(ranks_found)
            issue_summary["pass"] = True
        results["summary_by_issue"].append(issue_summary)

    return results


def generate_markdown_report(results: dict, output_path: Path) -> None:
    """Generate a markdown analysis report from the results following the standard format."""
    run_id = results["run_id"]
    path = results["path"]
    timestamp = results["timestamp"]
    config = results["config"]
    summary_by_issue = results["summary_by_issue"]
    errors = results["errors"]
    all_results = results["results"]
    
    # Calculate overall statistics
    total_queries = config["queries_count"]
    issues_count = config["issues_count"]
    
    # Use shared utility to calculate statistics
    stats = calculate_statistics(all_results)
    pass_rate = (stats["found_count"] / total_queries * 100) if total_queries > 0 else 0
    
    # Count issues with at least one style found
    issues_with_at_least_one_found = sum(1 for issue in summary_by_issue if issue["pass"])
    issues_fully_failing = issues_count - issues_with_at_least_one_found
    
    # Statistics by query style and locale
    style_stats = group_results_by_style(all_results)
    
    # Group results by locale
    locale_groups = defaultdict(lambda: defaultdict(list))
    for result in all_results:
        locale = result.get("query_locale", "en")
        style = result.get("query_style", "unknown")
        locale_groups[locale][style].append(result)
    
    # Build the markdown report
    lines = [
        f"# Algolia Search Results Analysis Report",
        f"",
        f"**Run ID:** {run_id}",
        f"**Run date:** {timestamp}",
        f"**Path:** {path}",
        f"**Algolia index:** {config['algolia_index']}",
        f"**Locale:** {config.get('locale', 'all')}",
        f"**Issues tested:** {issues_count}",
        f"**Total queries:** {total_queries}",
        f"**Top N results captured:** {config['top_n']}",
        f"",
        f"---",
        f"",
        f"## Overall Performance",
        f"",
        f"- **Pass rate:** {pass_rate:.1f}% ({stats['found_count']}/{total_queries} queries found target doc)",
        f"- **Average rank when found:** {stats['avg_rank']:.1f}" if stats['ranks'] else "- **Average rank when found:** N/A (no documents found)",
        f"- **Issues with at least one style found:** {issues_with_at_least_one_found}/{issues_count}",
        f"- **Issues fully failing:** {issues_fully_failing}/{issues_count}",
        f"",
        f"## Performance by Query Style",
        f"",
        f"| Style | Found | Not Found | Avg Rank | Pass Rate |",
        f"|-------|-------|-----------|----------|-----------|",
    ]
    
    for style in ["naive", "familiar", "expert"]:
        style_results = style_stats.get(style, [])
        if not style_results:
            continue
        
        # Use shared utility to calculate style statistics
        style_calc = calculate_statistics(style_results)
        style_pass_rate = (style_calc['found_count'] / len(style_results) * 100) if style_results else 0
        
        lines.append(f"| {style.capitalize()} | {style_calc['found_count']} | {style_calc['not_found_count']} | {style_calc['avg_rank']:.1f} | {style_pass_rate:.1f}% |")
    
    # Performance by Locale
    lines.extend([
        f"",
        f"## Performance by Locale",
        f"",
        f"| Locale | Found | Not Found | Avg Rank | Pass Rate |",
        f"|--------|-------|-----------|----------|-----------|",
    ])
    
    for locale in sorted(locale_groups.keys()):
        locale_results = []
        for style in ["naive", "familiar", "expert"]:
            if style in locale_groups[locale]:
                locale_results.extend(locale_groups[locale][style])
        
        if locale_results:
            locale_stats = calculate_statistics(locale_results)
            locale_pass_rate = (locale_stats['found_count'] / len(locale_results) * 100) if locale_results else 0
            avg_rank_str = f"{locale_stats['avg_rank']:.1f}" if locale_stats['ranks'] else "0.0"
            
            lines.append(f"| {locale} | {locale_stats['found_count']} | {locale_stats['not_found_count']} | {avg_rank_str} | {locale_pass_rate:.1f}% |")
    
    # Detailed Results by Locale and Query
    lines.extend([
        f"",
        f"## Detailed Results by Locale and Query",
        f"",
    ])
    
    for locale in sorted(locale_groups.keys()):
        locale_upper = locale.upper()
        lines.extend([
            f"### {locale_upper} ({locale.capitalize()})",
            f"",
        ])
        
        for style in ["naive", "familiar", "expert"]:
            if style not in locale_groups[locale]:
                continue
            
            for result in locale_groups[locale][style]:
                query_text = result.get("query", "")
                found = result.get("found", False)
                found_at_rank = result.get("found_at_rank")
                status = f"✓ (rank {found_at_rank})" if found else "✗"
                
                lines.extend([
                    f"**{style.capitalize()} query:** \"{query_text}\" {status}",
                    f"",
                ])
                
                # Show top results (limit to 7, deduplicated by document)
                top_results = result.get("top_results", [])
                if top_results:
                    # Deduplicate results to show unique documents only
                    unique_results = deduplicate_results_by_document(top_results, max_results=7)
                    
                    lines.append(f"Top {len(unique_results)} unique document(s):")
                    lines.append(f"")
                    
                    for top_result in unique_results:
                        rank = top_result.get("rank", "?")
                        title = top_result.get("title", "")
                        url = top_result.get("url", "")
                        lines.append(f"{rank}. [{title}]({url})")
                    
                    lines.append(f"")
                else:
                    lines.append(f"*No results returned*")
                    lines.append(f"")
                lines.append(f"")
    
    # Issues Requiring Attention
    lines.extend([
        f"## Issues Requiring Attention",
        f"",
    ])
    
    # Failed all query styles
    failed_issues = [issue for issue in summary_by_issue if not issue["pass"]]
    if failed_issues:
        lines.append(f"### Failed All Query Styles ({len(failed_issues)} issues)")
        lines.append(f"")
        for issue in failed_issues:
            lines.append(f"**{issue['issue_id']}**")
            lines.append(f"- Target: {issue.get('target_doc_url', issue.get('expected_doc_url', 'N/A'))}")
            lines.append(f"- All query styles: not found")
            lines.append(f"")
    else:
        lines.append(f"*No issues failed all query styles.*")
        lines.append(f"")
    
    # Errors encountered
    lines.extend([
        f"",
        f"## Errors Encountered",
        f"",
    ])
    
    if errors:
        lines.append(f"| Issue ID | Query Style | Error Type | Message |")
        lines.append(f"|----------|-------------|------------|---------|")
        for error in errors:
            error_msg = truncate_text(error['error_message'], ERROR_MESSAGE_MAX_LENGTH)
            lines.append(f"| {error['issue_id']} | {error['query_style']} | {error['error_type']} | {error_msg} |")
    else:
        lines.append(f"*No errors encountered.*")
    
    lines.append(f"")
    
    # Footer
    lines.extend([
        f"",
        f"---",
        f"",
        f"*Generated by Algolia Path Runner on {timestamp}*",
    ])
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Run Algolia path tests (Help Center and/or Dev Portal)"
    )
    parser.add_argument(
        "--path",
        choices=["helpcenter", "devportal", "both"],
        default="both",
        help="Which path(s) to run (default: both)",
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="Run identifier (default: algolia-{path}-run-YYYY-MM-DD-HHmmss)",
    )
    parser.add_argument(
        "--issues",
        nargs="*",
        default=None,
        help="Space-separated issue IDs to filter (default: all)",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=10,
        help="Number of top results to capture (default: 10)",
    )
    parser.add_argument(
        "--output-dir",
        default="results/internal-search",
        help="Base output directory (default: results/internal-search)",
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=0.5,
        help="Delay between API calls in seconds (default: 0.5)",
    )
    parser.add_argument(
        "--locale",
        default="all",
        help="Locale filter for search (default: all, options: en, es, pt, all)",
    )
    parser.add_argument(
        "--no-analysis",
        action="store_true",
        help="Skip per-index markdown analysis reports (generated by default)",
    )
    args = parser.parse_args()

    app_id = (
        os.environ.get("ALGOLIA_APP_ID", "").strip()
        or os.environ.get("NEXT_PUBLIC_ALGOLIA_APP_ID", "").strip()
    )
    api_key = (
        os.environ.get("ALGOLIA_SEARCH_API_KEY", "").strip()
        or os.environ.get("ALGOLIA_SEARCH_KEY", "").strip()
        or os.environ.get("NEXT_PUBLIC_ALGOLIA_WRITE_KEY", "").strip()
    )

    if not app_id or not api_key:
        print(
            "Error: Set ALGOLIA_APP_ID (or NEXT_PUBLIC_ALGOLIA_APP_ID) and one of "
            "ALGOLIA_SEARCH_API_KEY, ALGOLIA_SEARCH_KEY, or NEXT_PUBLIC_ALGOLIA_WRITE_KEY.",
            file=sys.stderr,
        )
        return 1

    workspace = _script_dir.parent.parent.parent
    issues_dir = workspace / "docs" / "test-suite" / "issues"
    all_queries_json = workspace / "data" / "test-suite" / "internal-search" / "all_queries.json"
    
    # Use all_queries.json if it exists, otherwise fall back to loading from individual issue files
    if all_queries_json.exists():
        print(f"Loading queries from: {all_queries_json}")
        
        # Locale filtering strategy:
        # - helpcenter-docs: supports all locales (en, pt, es)
        # - devportal-docs: supports ONLY 'en' locale
        # When running --path both, we load all queries and filter per-index in run_one_path()
        
        if args.path == "helpcenter":
            # For helpcenter only: respect user's locale preference
            locale_filter = args.locale if args.locale != "all" else None
            if locale_filter:
                print(f"Filtering queries for locale: {locale_filter}")
            else:
                print(f"Running queries for all locales (helpcenter-docs supports en, pt, es)")
            issues = load_issues_from_all_queries_json(all_queries_json, issues_dir, args.issues, locale_filter=locale_filter)
        elif args.path == "devportal":
            # For devportal only: always filter to 'en' (devportal limitation)
            if args.locale not in ["en", "all"]:
                print(f"Warning: devportal-docs only supports 'en' locale. Ignoring --locale {args.locale}")
            print(f"Filtering queries for locale: en (devportal-docs supports only English)")
            issues = load_issues_from_all_queries_json(all_queries_json, issues_dir, args.issues, locale_filter="en")
        else:  # both
            # For both indexes: load all queries, filter per-index in run_one_path()
            # This allows helpcenter to use all locales while devportal uses only 'en'
            locale_filter = args.locale if args.locale != "all" else None
            if locale_filter:
                print(f"Locale setting: {args.locale}")
                print(f"  - helpcenter-docs: {args.locale}")
                print(f"  - devportal-docs: en only (index supports only English)")
            else:
                print(f"Running queries for all locales")
                print(f"  - helpcenter-docs: all locales (en, pt, es)")
                print(f"  - devportal-docs: en only (index supports only English)")
            issues = load_issues_from_all_queries_json(all_queries_json, issues_dir, args.issues, locale_filter=locale_filter)
    else:
        print(f"Warning: all_queries.json not found, loading from individual issue files in: {issues_dir}")
        issues = load_issues_from_directory(issues_dir, args.issues)

    print(f"\nLoaded {len(issues)} issues with query_internal")

    if not issues:
        print("No issues to run.")
        return 0
    
    base_output = workspace / args.output_dir
    
    # Validate output directory before running tests
    if not validate_output_directory(base_output):
        return 1

    paths_to_run = []
    if args.path == "both":
        paths_to_run = [
            ("helpcenter", ALGOLIA_INDEX_HELPCENTER),
            ("devportal", ALGOLIA_INDEX_DEVPORTAL),
        ]
    elif args.path == "helpcenter":
        paths_to_run = [("helpcenter", ALGOLIA_INDEX_HELPCENTER)]
    else:
        paths_to_run = [("devportal", ALGOLIA_INDEX_DEVPORTAL)]

    base_output = workspace / args.output_dir
    run_started_at = datetime.now()

    # Store results for APIs comparison (and optional hybrid)
    all_path_results = {}

    for path_name, index_name in paths_to_run:
        path_slug = f"algolia-{path_name}"
        run_id = args.run_id or f"{path_slug}-run-{run_started_at.strftime('%Y-%m-%d-%H%M%S')}"
        print(f"\n{'='*50}\nAlgolia path: {path_name} (index: {index_name})\n{'='*50}")
        results = run_one_path(
            path_name=path_name,
            index_name=index_name,
            issues=issues,
            application_id=app_id,
            api_key=api_key,
            run_id=run_id,
            top_n=args.top_n,
            delay=args.delay,
            locale=args.locale,
        )
        
        # Store results for APIs comparison
        all_path_results[path_name] = results
        
        run_dir = create_run_directory(base_output, path_slug, run_started_at)
        json_path = run_dir / f"{run_id}.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)
        print(f"\nResults saved to: {json_path}")
        print(f"  Queries: {results['config']['queries_count']}, Errors: {len(results['errors'])}")
        
        # Generate per-index markdown analysis report (enabled by default)
        if not args.no_analysis:
            md_path = run_dir / f"analysis-{run_id}.md"
            generate_markdown_report(results, md_path)
            print(f"Per-index analysis report saved to: {md_path}")
    
    if args.no_analysis and paths_to_run:
        print("Note: Per-index analysis reports were skipped. Remove --no-analysis to generate them.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
