#!/usr/bin/env python3
"""
VTEX Docs Hybrid Search API Path Runner

Runs queries from all_queries.json against the VTEX Docs Hybrid Search API.
Outputs results in the unified format documented in
docs/test-suite/results-layout.md.

Query source: data/test-suite/internal-search/all_queries.json (Internal search path)
Fallback: Individual issue files from docs/test-suite/issues/ (if all_queries.json not found)

Usage:
    python tools/test-suite/internal-search/run-hybrid-search-path.py [options]

Options:
    --run-id TEXT                     Run identifier (default: hybrid-search-run-YYYY-MM-DD-HHmmss)
    --issues TEXT                     Space-separated issue IDs to filter (default: all)
    --top-n INT                       Number of top results to capture (default: 10)
    --output-dir TEXT                 Base output directory (default: results/internal-search)
    --delay FLOAT                     Delay between API calls in seconds (default: 0.5)
    --locale TEXT                     Locale filter for search (default: all, options: en, es, pt, all)
    --no-analysis                     Skip markdown analysis report (generated by default)
    --generate-api-call-results       Generate internal search comparison report (includes Algolia if present)

Environment (required):
    HYBRID_SEARCH_API_URL             Base URL for the Hybrid Search API
                                      Production: https://vtexdocs-edge.vtex.com
                                      Local dev: http://localhost:3000
    HYBRID_SEARCH_INTERNAL_KEY        Internal access key for authentication
"""

import os
import sys
import re
import json
import time
import urllib.request
import urllib.parse
import urllib.error
import ssl
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from collections import defaultdict

# Add current directory to path for shared utilities (test_runner_utils.py is in the same directory)
_script_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(_script_dir))

# Import shared utilities
from test_runner_utils import (
    load_env_file,
    parse_issue_file,
    normalize_url,
    check_expected_doc_found,
    truncate_text,
    validate_output_directory,
    load_issues_from_directory,
    load_issues_from_all_queries_json,
    format_result_for_display,
    calculate_statistics,
    group_results_by_style,
    generate_apis_comparison_analysis,
    deduplicate_results_by_document,
    TITLE_MAX_LENGTH,
    URL_DISPLAY_MAX_LENGTH,
    QUERY_DISPLAY_MAX_LENGTH,
    ERROR_MESSAGE_MAX_LENGTH,
)

# Load environment variables from .env file if it exists
load_env_file()


def create_run_directory(base_output: Path, path_slug: str, timestamp: datetime | None = None) -> Path:
    """Create a per-run output folder under results/internal-search/<variant>/."""
    ts = timestamp or datetime.now()
    folder_name = f"{path_slug} {ts.strftime('%Y-%m-%d %H-%M')}"
    variant_root = base_output / path_slug
    run_dir = variant_root / folder_name
    if not run_dir.exists():
        run_dir.mkdir(parents=True, exist_ok=False)
        return run_dir

    suffix = 2
    while True:
        candidate = variant_root / f"{folder_name} ({suffix})"
        if not candidate.exists():
            candidate.mkdir(parents=True, exist_ok=False)
            return candidate
        suffix += 1


def load_latest_algolia_results(base_output: Path) -> tuple[Optional[dict], Optional[dict]]:
    """Load the most recent Algolia results JSON for each index from nested run folders."""

    def load_latest_for_path(expected_path: str) -> Optional[dict]:
        jsons = [
            p for p in base_output.rglob("*.json")
            if p.is_file() and not p.name.startswith("analysis-")
        ]
        candidates = []
        for json_path in jsons:
            try:
                with open(json_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                if data.get("path") == expected_path and "results" in data:
                    candidates.append((json_path.stat().st_mtime, data))
            except (json.JSONDecodeError, OSError):
                continue
        if not candidates:
            return None
        return max(candidates, key=lambda item: item[0])[1]

    return (
        load_latest_for_path("algolia-helpcenter"),
        load_latest_for_path("algolia-devportal"),
    )


def call_hybrid_search_api(
    base_url: str,
    internal_key: str,
    query: str,
    limit: int = 10,
    locale: str = "en",
    timeout: int = 30,
) -> tuple[list[dict], list[str]]:
    """
    Call VTEX Docs Hybrid Search API (GET /api/hybrid-search).

    Returns:
        Tuple of (list of result dicts, list of error strings).
    """
    # Build URL with query parameters
    url = f"{base_url}/api/hybrid-search?q={urllib.parse.quote(query)}&limit={limit}&locale={locale}"

    headers = {
        "x-internal-access-key": internal_key,
        "Content-Type": "application/json",
    }

    errors = []
    try:
        ctx = ssl.create_default_context()
        req = urllib.request.Request(url, headers=headers, method="GET")
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        errors.append(f"HTTP {e.code}: {e.reason}")
        return [], errors
    except urllib.error.URLError as e:
        errors.append(f"URL error: {e.reason}")
        return [], errors
    except TimeoutError:
        errors.append(f"Request timed out after {timeout}s")
        return [], errors
    except Exception as e:
        errors.append(str(e))
        return [], errors

    results = data.get("results") or []
    return results, []


def build_canonical_url(result: dict) -> str:
    """Build canonical URL from result metadata."""
    repository = result.get("repository", "")
    file_path = result.get("filePath", "")
    metadata = result.get("metadata") or {}
    frontmatter = metadata.get("frontmatter") or {}
    slug = frontmatter.get("slug", "")

    # Determine base URL based on repository
    if "help-center" in repository.lower():
        base = "https://help.vtex.com"
    elif "dev-portal" in repository.lower() or "developers" in repository.lower():
        base = "https://developers.vtex.com"
    else:
        # Default to help center
        base = "https://help.vtex.com"

    # Build URL from slug if available
    if slug:
        return f"{base}/{slug}"

    # Otherwise try to build from file path
    if file_path:
        # Remove file extension and convert to URL path
        url_path = file_path.replace("\\", "/").rstrip(".md").rstrip(".mdx")
        return f"{base}/{url_path}"

    return base


def result_to_top_result(result: dict, rank: int) -> dict:
    """
    Map a hybrid search result to the full API response format.
    Includes all fields from the API response for complete transparency.
    """
    # Build canonical URL for backward compatibility and easy comparison
    url = build_canonical_url(result)
    
    # Return the complete API result structure
    return {
        "rank": rank,
        "id": result.get("id"),
        "title": result.get("title", ""),
        "filePath": result.get("filePath", ""),
        "chunkIndex": result.get("chunkIndex"),
        "repository": result.get("repository", ""),
        "snippet": result.get("snippet", ""),
        "content": result.get("content", ""),
        "score": result.get("score"),
        "metadata": result.get("metadata", {}),
        "url": url,  # Computed canonical URL for easy comparison
    }


def run_hybrid_search_path(
    issues: list[dict],
    base_url: str,
    internal_key: str,
    run_id: str,
    top_n: int,
    locale: str,
    delay: float,
) -> dict:
    """Run all query_internal queries for hybrid search path. Return unified results dict."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    path_slug = "hybrid-search"

    results = {
        "run_id": run_id,
        "path": path_slug,
        "timestamp": timestamp,
        "config": {
            "api_url": base_url,
            "locale": locale,
            "top_n": top_n,
            "issues_count": len(issues),
            "queries_count": sum(len(i.get("query_internal", [])) for i in issues),
        },
        "summary_by_issue": [],
        "errors": [],
        "results": [],
    }

    total_issues = len(issues)

    for issue_idx, issue in enumerate(issues, start=1):
        issue_id = issue["issue_id"]
        target_url = issue.get("target_doc_url", issue.get("expected_doc_url", ""))
        queries = issue.get("query_internal", [])

        print(f"\n[Issue {issue_idx}/{total_issues}] {issue_id}")

        issue_summary = {
            "issue_id": issue_id,
            "target_doc_url": target_url,
            "expected_doc_url": target_url,
            "results_by_style": {},
            "best_rank": None,
            "worst_rank": None,
            "pass": False,
        }
        ranks_found = []

        for query_idx, qo in enumerate(queries, start=1):
            query_text = qo.get("query", "")
            query_style = qo.get("style", "unknown")
            query_locale = qo.get("locale", locale or "en")  # Use query-specific locale or fallback

            print(f"  [{query_idx}/{len(queries)} ({query_style}, {query_locale})] {query_text[:50]}...")

            time.sleep(delay)

            search_results, api_errors = call_hybrid_search_api(
                base_url, internal_key, query_text, limit=top_n, locale=query_locale
            )

            if api_errors:
                print(f"    ERROR: {api_errors[0]}")
                results["errors"].append(
                    {
                        "issue_id": issue_id,
                        "query": query_text,
                        "query_style": query_style,
                        "error_type": "api_call_failed",
                        "error_message": api_errors[0],
                    }
                )
                results["results"].append(
                    {
                        "issue_id": issue_id,
                        "path": path_slug,
                        "query": query_text,
                        "query_style": query_style,
                        "query_locale": query_locale,
                        "target_doc_url": target_url,
                        "expected_doc_url": target_url,
                        "found": False,
                        "found_at_rank": None,
                        "top_results": [],
                    }
                )
                issue_summary["results_by_style"][query_style] = {
                    "found": False,
                    "rank": None,
                }
                continue

            top_results = [
                result_to_top_result(result, i)
                for i, result in enumerate(search_results[:top_n], start=1)
            ]
            found, found_at_rank = check_expected_doc_found(top_results, target_url)
            status = f"found at rank {found_at_rank}" if found else "not found"
            print(f"    -> {len(search_results)} results | Target doc: {status}")

            results["results"].append(
                {
                    "issue_id": issue_id,
                    "path": path_slug,
                    "query": query_text,
                    "query_style": query_style,
                    "query_locale": query_locale,
                    "target_doc_url": target_url,
                    "expected_doc_url": target_url,
                    "found": found,
                    "found_at_rank": found_at_rank,
                    "target_doc_url_found": found,
                    "target_doc_url_rank": found_at_rank,
                    "top_results": top_results,
                }
            )
            issue_summary["results_by_style"][query_style] = {
                "found": found,
                "rank": found_at_rank,
            }
            if found and found_at_rank:
                ranks_found.append(found_at_rank)

        if ranks_found:
            issue_summary["best_rank"] = min(ranks_found)
            issue_summary["worst_rank"] = max(ranks_found)
            issue_summary["pass"] = True
        results["summary_by_issue"].append(issue_summary)

    return results


def generate_markdown_report(results: dict, output_path: Path) -> None:
    """Generate a markdown analysis report from the results following the standard format."""
    run_id = results["run_id"]
    path = results["path"]
    timestamp = results["timestamp"]
    config = results["config"]
    summary_by_issue = results["summary_by_issue"]
    errors = results["errors"]
    all_results = results["results"]
    
    # Calculate overall statistics
    total_queries = config["queries_count"]
    issues_count = config["issues_count"]
    
    # Use shared utility to calculate statistics
    stats = calculate_statistics(all_results)
    pass_rate = (stats["found_count"] / total_queries * 100) if total_queries > 0 else 0
    
    # Count issues with at least one style found
    issues_with_at_least_one_found = sum(1 for issue in summary_by_issue if issue["pass"])
    issues_fully_failing = issues_count - issues_with_at_least_one_found
    
    # Statistics by query style and locale
    style_stats = group_results_by_style(all_results)
    
    # Group results by locale
    locale_groups = defaultdict(lambda: defaultdict(list))
    for result in all_results:
        locale = result.get("query_locale", "en")
        style = result.get("query_style", "unknown")
        locale_groups[locale][style].append(result)
    
    # Build the markdown report
    lines = [
        f"# Hybrid Search Results Analysis Report",
        f"",
        f"**Run ID:** {run_id}",
        f"**Run date:** {timestamp}",
        f"**Path:** {path}",
        f"**API endpoint:** {config['api_url']}/api/hybrid-search",
        f"**Locale:** {config['locale']}",
        f"**Issues tested:** {issues_count}",
        f"**Total queries:** {total_queries}",
        f"**Top N results captured:** {config['top_n']}",
        f"",
        f"---",
        f"",
        f"## Overall Performance",
        f"",
        f"- **Pass rate:** {pass_rate:.1f}% ({stats['found_count']}/{total_queries} queries found target doc)",
        f"- **Average rank when found:** {stats['avg_rank']:.1f}" if stats['ranks'] else "- **Average rank when found:** N/A (no documents found)",
        f"- **Issues with at least one style found:** {issues_with_at_least_one_found}/{issues_count}",
        f"- **Issues fully failing:** {issues_fully_failing}/{issues_count}",
        f"",
        f"## Performance by Query Style",
        f"",
        f"| Style | Found | Not Found | Avg Rank | Pass Rate |",
        f"|-------|-------|-----------|----------|-----------|",
    ]
    
    for style in ["naive", "familiar", "expert"]:
        style_results = style_stats.get(style, [])
        if not style_results:
            continue
        
        # Use shared utility to calculate style statistics
        style_calc = calculate_statistics(style_results)
        style_pass_rate = (style_calc['found_count'] / len(style_results) * 100) if style_results else 0
        
        lines.append(f"| {style.capitalize()} | {style_calc['found_count']} | {style_calc['not_found_count']} | {style_calc['avg_rank']:.1f} | {style_pass_rate:.1f}% |")
    
    # Performance by Locale
    lines.extend([
        f"",
        f"## Performance by Locale",
        f"",
        f"| Locale | Found | Not Found | Avg Rank | Pass Rate |",
        f"|--------|-------|-----------|----------|-----------|",
    ])
    
    for locale in sorted(locale_groups.keys()):
        locale_results = []
        for style in ["naive", "familiar", "expert"]:
            if style in locale_groups[locale]:
                locale_results.extend(locale_groups[locale][style])
        
        if locale_results:
            locale_stats = calculate_statistics(locale_results)
            locale_pass_rate = (locale_stats['found_count'] / len(locale_results) * 100) if locale_results else 0
            avg_rank_str = f"{locale_stats['avg_rank']:.1f}" if locale_stats['ranks'] else "0.0"
            
            lines.append(f"| {locale} | {locale_stats['found_count']} | {locale_stats['not_found_count']} | {avg_rank_str} | {locale_pass_rate:.1f}% |")
    
    # Detailed Results by Locale and Query
    lines.extend([
        f"",
        f"## Detailed Results by Locale and Query",
        f"",
    ])
    
    for locale in sorted(locale_groups.keys()):
        locale_upper = locale.upper()
        lines.extend([
            f"### {locale_upper} ({locale.capitalize()})",
            f"",
        ])
        
        for style in ["naive", "familiar", "expert"]:
            if style not in locale_groups[locale]:
                continue
            
            for result in locale_groups[locale][style]:
                query_text = result.get("query", "")
                found = result.get("found", False)
                found_at_rank = result.get("found_at_rank")
                status = f"✓ (rank {found_at_rank})" if found else "✗"
                
                lines.extend([
                    f"**{style.capitalize()} query:** \"{query_text}\" {status}",
                    f"",
                ])
                
                # Show top results (limit to 7, deduplicated by document)
                top_results = result.get("top_results", [])
                if top_results:
                    # Deduplicate results to show unique documents only
                    unique_results = deduplicate_results_by_document(top_results, max_results=7)
                    
                    lines.append(f"Top {len(unique_results)} unique document(s):")
                    lines.append(f"")
                    
                    for top_result in unique_results:
                        rank = top_result.get("rank", "?")
                        title = top_result.get("title", "")
                        url = top_result.get("url", "")
                        lines.append(f"{rank}. [{title}]({url})")
                    
                    lines.append(f"")
                else:
                    lines.append(f"*No results returned*")
                    lines.append(f"")
                lines.append(f"")
    
    # Issues Requiring Attention
    lines.extend([
        f"## Issues Requiring Attention",
        f"",
    ])
    
    # Failed all query styles
    failed_issues = [issue for issue in summary_by_issue if not issue["pass"]]
    if failed_issues:
        lines.append(f"### Failed All Query Styles ({len(failed_issues)} issues)")
        lines.append(f"")
        for issue in failed_issues:
            lines.append(f"**{issue['issue_id']}**")
            lines.append(f"- Target: {issue.get('target_doc_url', issue.get('expected_doc_url', 'N/A'))}")
            lines.append(f"- All query styles: not found")
            lines.append(f"")
    else:
        lines.append(f"*No issues failed all query styles.*")
        lines.append(f"")
    
    # Errors encountered
    lines.extend([
        f"",
        f"## Errors Encountered",
        f"",
    ])
    
    if errors:
        lines.append(f"| Issue ID | Query Style | Error Type | Message |")
        lines.append(f"|----------|-------------|------------|---------|")
        for error in errors:
            error_msg = truncate_text(error['error_message'], ERROR_MESSAGE_MAX_LENGTH)
            lines.append(f"| {error['issue_id']} | {error['query_style']} | {error['error_type']} | {error_msg} |")
    else:
        lines.append(f"*No errors encountered.*")
    
    lines.append(f"")
    
    # Footer
    lines.extend([
        f"",
        f"---",
        f"",
        f"*Generated by Hybrid Search Path Runner on {timestamp}*",
    ])
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Run VTEX Docs Hybrid Search API path tests"
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="Run identifier (default: hybrid-search-run-YYYY-MM-DD-HHmmss)",
    )
    parser.add_argument(
        "--issues",
        nargs="*",
        default=None,
        help="Space-separated issue IDs to filter (default: all)",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=10,
        help="Number of top results to capture (default: 10)",
    )
    parser.add_argument(
        "--output-dir",
        default="results/internal-search",
        help="Base output directory (default: results/internal-search)",
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=0.5,
        help="Delay between API calls in seconds (default: 0.5)",
    )
    parser.add_argument(
        "--locale",
        default="all",
        help="Locale filter for search (default: all, options: en, es, pt, all)",
    )
    parser.add_argument(
        "--no-analysis",
        action="store_true",
        help="Skip markdown analysis report (generated by default)",
    )
    parser.add_argument(
        "--generate-api-call-results",
        action="store_true",
        help="Generate internal search comparison report (includes Algolia if present)",
    )
    args = parser.parse_args()

    base_url = os.environ.get("HYBRID_SEARCH_API_URL", "").strip()
    internal_key = os.environ.get("HYBRID_SEARCH_INTERNAL_KEY", "").strip()

    if not base_url or not internal_key:
        print(
            "Error: Set HYBRID_SEARCH_API_URL and HYBRID_SEARCH_INTERNAL_KEY environment variables.",
            file=sys.stderr,
        )
        return 1

    workspace = _script_dir.parent.parent.parent
    issues_dir = workspace / "docs" / "test-suite" / "issues"
    all_queries_json = workspace / "data" / "test-suite" / "internal-search" / "all_queries.json"
    
    # Use all_queries.json if it exists, otherwise fall back to loading from individual issue files
    if all_queries_json.exists():
        print(f"Loading queries from: {all_queries_json}")
        # Pass locale filter to load only queries for the specified locale
        locale_filter = args.locale if args.locale != "all" else None
        if locale_filter:
            print(f"Filtering queries for locale: {locale_filter}")
        else:
            print(f"Running queries for all locales (as specified in all_queries.json)")
        issues = load_issues_from_all_queries_json(all_queries_json, issues_dir, args.issues, locale_filter=locale_filter)
    else:
        print(f"Warning: all_queries.json not found, loading from individual issue files in: {issues_dir}")
        issues = load_issues_from_directory(issues_dir, args.issues)

    print(f"\nLoaded {len(issues)} issues with query_internal")

    if not issues:
        print("No issues to run.")
        return 0

    base_output = workspace / args.output_dir
    
    # Validate output directory before running tests
    if not validate_output_directory(base_output):
        return 1
    
    run_started_at = datetime.now()
    run_id = args.run_id or f"hybrid-search-run-{run_started_at.strftime('%Y-%m-%d-%H%M%S')}"

    print(f"\n{'='*50}\nHybrid Search API Path\n{'='*50}")
    results = run_hybrid_search_path(
        issues=issues,
        base_url=base_url,
        internal_key=internal_key,
        run_id=run_id,
        top_n=args.top_n,
        locale=args.locale,
        delay=args.delay,
    )

    run_dir = create_run_directory(base_output, "hybrid-search", run_started_at)
    json_path = run_dir / f"{run_id}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    print(f"\nResults saved to: {json_path}")
    print(f"  Queries: {results['config']['queries_count']}, Errors: {len(results['errors'])}")

    # Generate markdown analysis report (enabled by default)
    if not args.no_analysis:
        md_path = run_dir / f"analysis-{run_id}.md"
        generate_markdown_report(results, md_path)
        print(f"Analysis report saved to: {md_path}")
    else:
        print("Note: Analysis report was skipped. Remove --no-analysis to generate it.")

    # Generate combined API call results report if requested
    if args.generate_api_call_results:
        helpcenter_results, devportal_results = load_latest_algolia_results(base_output)
        if helpcenter_results and devportal_results:
            comparison_path = run_dir / f"internal-search-comparison-{run_started_at.strftime('%Y-%m-%d-%H%M%S')}.md"

            print(f"\n{'='*50}\nGenerating Internal Search Comparison Report (Algolia + Hybrid Search)\n{'='*50}")
            generate_apis_comparison_analysis(
                helpcenter_results,
                devportal_results,
                comparison_path,
                hybrid_results=results,
            )
            print(f"Internal search comparison report saved to: {comparison_path}")
        else:
            print("\nNote: Internal search comparison report requires both Algolia paths to be run first.")
            print("Run both Algolia paths, then use --generate-api-call-results to generate the combined report.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
